// Code generated by MockGen. DO NOT EDIT.
// Source: internal/git.go

// Package git is a generated GoMock package.
package git

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGitManager is a mock of GitManager interface.
type MockGitManager struct {
	ctrl     *gomock.Controller
	recorder *MockGitManagerMockRecorder
}

// MockGitManagerMockRecorder is the mock recorder for MockGitManager.
type MockGitManagerMockRecorder struct {
	mock *MockGitManager
}

// NewMockGitManager creates a new mock instance.
func NewMockGitManager(ctrl *gomock.Controller) *MockGitManager {
	mock := &MockGitManager{ctrl: ctrl}
	mock.recorder = &MockGitManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitManager) EXPECT() *MockGitManagerMockRecorder {
	return m.recorder
}

// Clone mocks base method.
func (m *MockGitManager) Clone(gitURL, cloneDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", gitURL, cloneDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockGitManagerMockRecorder) Clone(gitURL, cloneDir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockGitManager)(nil).Clone), gitURL, cloneDir)
}

// Worktree mocks base method.
func (m *MockGitManager) Worktree(cloneDir, version, dstDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Worktree", cloneDir, version, dstDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Worktree indicates an expected call of Worktree.
func (mr *MockGitManagerMockRecorder) Worktree(cloneDir, version, dstDir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Worktree", reflect.TypeOf((*MockGitManager)(nil).Worktree), cloneDir, version, dstDir)
}
