---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X {{ .ModulePath }}/cmd.date={{ .CommitDate }}
      - -X {{ .ModulePath }}/cmd.commit={{ .Commit }}
      - -X {{ .ModulePath }}/cmd.version={{ .Version }}
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - repository:
      owner: retr0h
      name: homebrew-tap
    folder: Formula
    goarm: "7"
    homepage: https://github.com/retr0h/go-gilt
    description: A GIT layering tool
    license: MIT
    test: |
      system "#{bin}/goreleaser -v"
    dependencies:
      - name: go
        type: optional
      - name: git
