---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X {{ .ModulePath }}/cmd.date={{ .CommitDate }}
      - -X {{ .ModulePath }}/cmd.commit={{ .Commit }}
      - -X {{ .ModulePath }}/cmd.version={{ .Version }}
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  divider: "---"
  sort: asc
  filters:
    exclude:
      - '^test:'
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "Features"
      regexp: "^.*?feat:.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*?fix:.*$"
      order: 1
    - title: Others
      order: 999
      subgroups:
      - title: "Chores"
        regexp: "^.*?chore:.*$"
        order: 1
      - title: "Docs"
        regexp: "^.*?docs:.*$"
        order: 2
      - title: "CI"
        regexp: "^.*?ci:.*$"
        order: 3
      - title: "Build"
        regexp: "^.*?build:.*$"
        order: 4
brews:
  - repository:
      owner: retr0h
      name: homebrew-tap
    folder: Formula
    goarm: "7"
    homepage: https://github.com/retr0h/go-gilt
    description: A GIT layering tool
    license: MIT
    test: |
      system "#{bin}/goreleaser -v"
    dependencies:
      - name: go
        type: optional
      - name: git
