---
name: release packages
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  # packages: write
  # issues: write
  # permission is mandatory for trusted publishing
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Wheels
        run: task build:wheel
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/whl/
